# Matrik
### Defininsi matrik
Matriks adalah suatu susunan bilangan real atau bilangan kompleks (atau elemen-elemen) yang disusun dalam baris dan kolom sehingga membentuk jajaran persegi panjang.
###Operasi Aritmatika Matrik
Operasi aritmatika matriks adalah operasi matematika yang melibatkan matriks, seperti penjumlahan, pengurangan, perkalian, dan determinan. Berikut adalah beberapa operasi aritmatika matriks yang umum:

1. Penjumlahan Matriks
Dua matriks dapat dijumlahkan jika memiliki ukuran yang sama. Operasinya dilakukan dengan menjumlahkan elemen-elemen yang bersesuaian.


4. Determinan Matriks
Determinan hanya bisa dihitung untuk matriks persegi (n × n). Untuk matriks 2×2,
Konsep Perjumlahan matrik

In [ ]:
from sympy.interactive.printing import init_printing
init_printing(use_unicode=False)
from sympy.matrices import Matrix, eye, zeros, ones, diag, GramSchmidt
A = Matrix([[1, 0, 0],
            [0, 3, 0]])

B = Matrix([[1, 0, 0],
            [3, 4, 0]])

print("Matrik A:", A)
print("Matrik B:", B)
C = A + B
print("C = A + B:", C)

Matrik A: Matrix([[1, 0, 0], [0, 3, 0]])
Matrik B: Matrix([[1, 0, 0], [3, 4, 0]])
C = A + B: Matrix([[2, 0, 0], [3, 7, 0]])


2. Pengurangan Matriks
Sama seperti penjumlahan, dua matriks dapat dikurangkan jika memiliki ukuran yang sama. Operasinya dilakukan dengan mengurangkan elemen-elemen yang bersesuaian.

In [1]:
import numpy as np
A = np.array([[5, 8, 3],
              [4, 6, 2],
              [7, 9, 1]])

B = np.array([[2, 3, 1],
              [1, 5, 0],
              [4, 2, 3]])
C = A - B
print("Matriks A:\n", A)
print("Matriks B:\n", B)
print("Hasil Pengurangan (A - B):\n", C)


Matriks A:
 [[5 8 3]
 [4 6 2]
 [7 9 1]]
Matriks B:
 [[2 3 1]
 [1 5 0]
 [4 2 3]]
Hasil Pengurangan (A - B):
 [[ 3  5  2]
 [ 3  1  2]
 [ 3  7 -2]]


3. Perkalian Matriks
Ada beberapa jenis perkalian matriks:

    a. Perkalian Skalar dengan Matriks
    Setiap elemen dalam matriks dikalikan dengan suatu bilangan skalar.


In [2]:
import numpy as np
A = np.array([[2, 4],
              [6, 8]])
k = 3
C = k * A
print("Matriks A:\n", A)
print("Skalar k:", k)
print("Hasil Perkalian k * A:\n", C)


Matriks A:
 [[2 4]
 [6 8]]
Skalar k: 3
Hasil Perkalian k * A:
 [[ 6 12]
 [18 24]]


b. Perkalian Dua Matriks
    Dua matriks dapat dikalikan jika jumlah kolom matriks pertama sama dengan jumlah baris matriks kedua. Perkalian dilakukan dengan menjumlahkan hasil kali elemen-elemen pada baris pertama dengan elemen-elemen pada kolom kedua.



In [3]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

C = np.dot(A, B)
print("Matriks A:\n", A)
print("Matriks B:\n", B)
print("Hasil Perkalian A * B:\n", C)


Matriks A:
 [[1 2 3]
 [4 5 6]]
Matriks B:
 [[ 7  8]
 [ 9 10]
 [11 12]]
Hasil Perkalian A * B:
 [[ 58  64]
 [139 154]]
